name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: target
          
      - name: Deploy to Netlify
        env:
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_NAME: 'react-js-project'
        run: |
          curl -X POST "https://api.netlify.com/api/v1/sites" \
            -H "Authorization: Bearer $NETLIFY_API_TOKEN" \
            -d '{
              "name": "'"$NETLIFY_SITE_NAME"'",
              "repo": "Badari103/ ReactJsGithubActions",
              "repoPath": "target",
              "buildSettings": {
                "command": "npm ci && npm run build",
                "publish": "target"
              }
            }'
